# Generated by Django 5.2.17 on 2026-09-13 11:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], db_index=True, default='QUEUED', max_length=16)),
                ('stage', models.CharField(blank=True, default='', max_length=32)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('source_key', models.CharField(max_length=1024)),
                ('file_type', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'XLSX')], max_length=8)),
                ('target_columns', models.JSONField(default=list)),
                ('transform_type', models.CharField(choices=[('regex_replace', 'Regex replace')], default='regex_replace', max_length=32)),
                ('pattern', models.TextField()),
                ('replacement_value', models.TextField(blank=True, default='')),
                ('result_path', models.CharField(blank=True, default='', max_length=1024)),
                ('row_count', models.BigIntegerField(blank=True, null=True)),
                ('matched_count', models.BigIntegerField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('error_message', models.TextField(blank=True, default='')),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
