# Generated by Django 5.2.17 on 2026-09-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_llm_cached_job_nl_prompt_job_pattern_explanation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='cancel_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
