# Generated by Django 5.2.17 on 2026-09-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_cancel_requested_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='transform_spec',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='transform_type',
            field=models.CharField(choices=[('regex_replace', 'Find and replace'), ('normalize_format', 'Normalize format'), ('mask_pii', 'Mask personal data')], default='regex_replace', max_length=32),
        ),
    ]
