# Generated by Django 5.2.17 on 2026-09-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_transform_spec_alter_job_transform_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='connection_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='job',
            name='source_bucket',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
